import re
def extract_sql_query(text):
    code_block_pattern = re.compile(r'```sql\s*(.*?)\s*```', re.DOTALL | re.IGNORECASE)
    code_block_match = code_block_pattern.search(text)
    if code_block_match:
        return code_block_match.group(1).strip()

    sql_keyword_pattern = re.compile(r"""
        \b(SELECT|INSERT|UPDATE|DELETE|CREATE\s+TABLE|DROP\s+TABLE|ALTER\s+TABLE|TRUNCATE|
        PRAGMA|COPY|GRANT|REVOKE|COMMENT|ANALYZE|VACUUM|CLUSTER|DISCARD|EXPLAIN|LISTEN|NOTIFY|
        UNLISTEN|SET|RESET|SHOW|START\s+TRANSACTION|BEGIN|COMMIT|ROLLBACK|SAVEPOINT|RELEASE\s+SAVEPOINT|
        PREPARE|EXECUTE|DEALLOCATE|DECLARE|FETCH|MOVE|CLOSE|DO|REINDEX|REFRESH\s+MATERIALIZED\s+VIEW|
        CREATE\s+EXTENSION|DROP\s+EXTENSION|CREATE\s+SCHEMA|DROP\s+SCHEMA|CREATE\s+SEQUENCE|DROP\s+SEQUENCE|
        CREATE\s+INDEX|DROP\s+INDEX|CREATE\s+VIEW|DROP\s+VIEW|CREATE\s+FUNCTION|DROP\s+FUNCTION|
        CREATE\s+TRIGGER|DROP\s+TRIGGER|CREATE\s+RULE|DROP\s+RULE|CREATE\s+AGGREGATE|DROP\s+AGGREGATE|
        CREATE\s+TYPE|DROP\s+TYPE|CREATE\s+DOMAIN|DROP\s+DOMAIN|CREATE\s+OPERATOR|DROP\s+OPERATOR|
        CREATE\s+LANGUAGE|DROP\s+LANGUAGE|CREATE\s+TEXT\s+SEARCH\s+CONFIGURATION|DROP\s+TEXT\s+SEARCH\s+CONFIGURATION|
        CREATE\s+TEXT\s+SEARCH\s+DICTIONARY|DROP\s+TEXT\s+SEARCH\s+DICTIONARY|CREATE\s+TEXT\s+SEARCH\s+PARSER|
        DROP\s+TEXT\s+SEARCH\s+PARSER|CREATE\s+TEXT\s+SEARCH\s+TEMPLATE|DROP\s+TEXT\s+SEARCH\s+TEMPLATE|
        CREATE\s+TABLESPACE|DROP\s+TABLESPACE|CREATE\s+USER\s+MAPPING|DROP\s+USER\s+MAPPING|
        CREATE\s+FOREIGN\s+TABLE|DROP\s+FOREIGN\s+TABLE|CREATE\s+SERVER|DROP\s+SERVER|
        CREATE\s+FOREIGN\s+DATA\s+WRAPPER|DROP\s+FOREIGN\s+DATA\s+WRAPPER|IMPORT\s+FOREIGN\s+SCHEMA|
        CREATE\s+PUBLICATION|DROP\s+PUBLICATION|CREATE\s+SUBSCRIPTION|DROP\s+SUBSCRIPTION|
        CREATE\s+TRANSFORM|DROP\s+TRANSFORM)\b.*?;
    """, re.IGNORECASE | re.DOTALL | re.VERBOSE)

    sql_keyword_match = sql_keyword_pattern.search(text)
    if sql_keyword_match:
        return sql_keyword_match.group(0).strip()

    return None